loomx.loom_version="1.16-SNAPSHOT"

mod.id = "combatlog"
mod.name = "CombatLog"
mod.group = "me.toastymop"
mod.version = "2.8.2"
mod.channel_tag = ""
mod.description = "This mod tries to prevent people from combat logging on a server."
mod.authors = ["WildToastyMop"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/WildToastyMop/CombatLog"
mod.homepage_url = "https://github.com/WildToastyMop/CombatLog"
mod.issues_url = "https://github.com/WildToastyMop/CombatLog/issues"
mod.discord_url = ""
[[mod.pom.developers]]
id = "wildtoastymop"
name = "WildToastyMop"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.9+1.20.1"
deps.modmenu = "lEkperf6"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "v6Xx3fbU"
publish.additionalVersions = ["1.21"]

[fabric."1.21.10"]
deps.minecraft = "1.21.10"
deps.fabric-api = "0.138.4+1.21.10"
deps.modmenu = "pYbFlVtR"
publish.additionalVersions = ["1.21.6", "1.21.7", "1.21.8", "1.21.9"]

[fabric."1.21.11"]
deps.minecraft = "1.21.11"
deps.fabric-api = "0.141.4+1.21.11"
deps.modmenu = "Tyk71iSw"

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "3rsoV1bk"
publish.additionalVersions = ["26.1", "26.1.1", "26.2"]

[forge]

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.4.20"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"
publish.additionalVersions = ["1.21"]

[neoforge."1.21.10"]
deps.minecraft = "1.21.10"
deps.neoforge = "21.10.64"
publish.additionalVersions = ["1.21.6", "1.21.7", "1.21.8", "1.21.9"]

[neoforge."1.21.11"]
deps.minecraft = "1.21.11"
deps.neoforge = "21.11.42"

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
publish.additionalVersions = ["26.1", "26.1.1", "26.2"]
